version: '3.7'
services:
  gatsby:
    build: 
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: ./entrypoint.sh
    ports:
      - "5000:8000"
    volumes:
     - .:/app
     - /app/node_modules/